/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import model.Empleado;
import org.json.JSONArray;

/**
 *
 * @author andres.giraldoy
 */
public class PrincipalEmpleadoView extends javax.swing.JFrame {

    JSONArray propietarios;
    JSONArray empleados;
    
    /**
     * Creates new form PrincipalEmpleadoView
     */
    public PrincipalEmpleadoView(JSONArray propietarios, JSONArray empleados, Empleado empleado) {
        initComponents();
        this.propietarios = propietarios;
        this.empleados = empleados;
        jButtonRegistrarEmpleado.setVisible(empleado.getCargo().equals("Administrador"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButtonRegistrarPropietario = new javax.swing.JButton();
        jButtonMulta = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jButtonRegistrarEmpleado = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Bienvenido");

        jButtonRegistrarPropietario.setBackground(new java.awt.Color(255, 164, 101));
        jButtonRegistrarPropietario.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButtonRegistrarPropietario.setText("Registrar propietario");
        jButtonRegistrarPropietario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarPropietarioActionPerformed(evt);
            }
        });

        jButtonMulta.setBackground(new java.awt.Color(255, 164, 101));
        jButtonMulta.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButtonMulta.setText("Realizar multa");
        jButtonMulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMultaActionPerformed(evt);
            }
        });

        jButtonSalir.setBackground(new java.awt.Color(188, 172, 161));
        jButtonSalir.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        jButtonRegistrarEmpleado.setBackground(new java.awt.Color(255, 164, 101));
        jButtonRegistrarEmpleado.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButtonRegistrarEmpleado.setText("Registrar Empleado");
        jButtonRegistrarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarEmpleadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonRegistrarPropietario)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jButtonSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonMulta, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE))
                            .addComponent(jButtonRegistrarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(jButtonRegistrarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonRegistrarPropietario, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonMulta, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRegistrarPropietarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarPropietarioActionPerformed
        // TODO add your handling code here:
        RegistrarPropietariosView registrarPropietariosFrame = new RegistrarPropietariosView(propietarios, empleados);
        registrarPropietariosFrame.setVisible(true);
        registrarPropietariosFrame.pack();
        registrarPropietariosFrame.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButtonRegistrarPropietarioActionPerformed

    private void jButtonMultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMultaActionPerformed
        // TODO add your handling code here:
        RealizarMultaView realizarMultaFrame = new RealizarMultaView(propietarios, empleados);
        realizarMultaFrame.setVisible(true);
        realizarMultaFrame.pack();
        realizarMultaFrame.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButtonMultaActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        // TODO add your handling code here:
        BienvenidaView BienvenidaFrame = new BienvenidaView();
        BienvenidaFrame.setVisible(true);
        BienvenidaFrame.pack();
        BienvenidaFrame.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonRegistrarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarEmpleadoActionPerformed
        // TODO add your handling code here:
        RegistrarEmpleadoView registrarUsuarioFrame = new RegistrarEmpleadoView(propietarios, empleados);
        registrarUsuarioFrame.setVisible(true);
        registrarUsuarioFrame.pack();
        registrarUsuarioFrame.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButtonRegistrarEmpleadoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonMulta;
    private javax.swing.JButton jButtonRegistrarEmpleado;
    private javax.swing.JButton jButtonRegistrarPropietario;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
