/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import model.Propietario;

/**
 *
 * @author yusti
 */
public class PrincipalUsuarioView extends javax.swing.JFrame {
    Propietario propietario;
    /**
     * Creates new form PrincipalUsuarioView
     */
    public PrincipalUsuarioView(Propietario propietario) {
        initComponents();
        this.propietario = propietario;
        System.out.println(propietario.getMultas());
        jLabelTitulo.setText("Bienvenid@ " + propietario.getNombre());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jButtonZonasComunes = new javax.swing.JButton();
        jButtonMultas = new javax.swing.JButton();
        jButtonFacturaTotal = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabelTitulo.setFont(new java.awt.Font("Segoe UI", 0, 82)); // NOI18N
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("Bienvenid@");
        jLabelTitulo.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 235;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(jLabelTitulo, gridBagConstraints);

        jButtonZonasComunes.setBackground(new java.awt.Color(255, 164, 101));
        jButtonZonasComunes.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButtonZonasComunes.setText("Horarios zonas comunes");
        jButtonZonasComunes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonZonasComunesActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(69, 199, 0, 0);
        jPanel1.add(jButtonZonasComunes, gridBagConstraints);

        jButtonMultas.setBackground(new java.awt.Color(255, 164, 101));
        jButtonMultas.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButtonMultas.setText("Multas");
        jButtonMultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMultasActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 189;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 199, 0, 0);
        jPanel1.add(jButtonMultas, gridBagConstraints);

        jButtonFacturaTotal.setBackground(new java.awt.Color(255, 164, 101));
        jButtonFacturaTotal.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButtonFacturaTotal.setText("Factura total");
        jButtonFacturaTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFacturaTotalActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 129;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 199, 0, 0);
        jPanel1.add(jButtonFacturaTotal, gridBagConstraints);

        jButtonSalir.setBackground(new java.awt.Color(188, 172, 161));
        jButtonSalir.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 216;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 199, 0, 0);
        jPanel1.add(jButtonSalir, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonZonasComunesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonZonasComunesActionPerformed
        // TODO add your handling code here:
        ZonasComunesView zonasComunesFrame = new ZonasComunesView();
        zonasComunesFrame.setVisible(true);
        zonasComunesFrame.pack();
        zonasComunesFrame.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButtonZonasComunesActionPerformed

    private void jButtonMultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMultasActionPerformed
        // TODO add your handling code here:
        VisualizarMultasView visualizarMultasFrame = new VisualizarMultasView(propietario);
        visualizarMultasFrame.setVisible(true);
        visualizarMultasFrame.pack();
        visualizarMultasFrame.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButtonMultasActionPerformed

    private void jButtonFacturaTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFacturaTotalActionPerformed
        // TODO add your handling code here:
        FacturaTotalView facturaTotalFrame = new FacturaTotalView(propietario);
        facturaTotalFrame.setVisible(true);
        facturaTotalFrame.pack();
        facturaTotalFrame.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButtonFacturaTotalActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        // TODO add your handling code here:
        BienvenidaView BienvenidaFrame = new BienvenidaView();
        BienvenidaFrame.setVisible(true);
        BienvenidaFrame.pack();
        BienvenidaFrame.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_jButtonSalirActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFacturaTotal;
    private javax.swing.JButton jButtonMultas;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JButton jButtonZonasComunes;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
